from __future__ import annotations

from datetime import datetime, timezone

from .schemas import (
    AsbestosRegisterItem,
    AuditEvent,
    EstimatorEdit,
    PricingRule,
    QuoteLine,
    QuoteWorkup,
    RiskFlag,
    SourceDocument,
    SourceEvidence,
)


NOW = datetime(2026, 5, 23, 9, 0, tzinfo=timezone.utc)
WORKUP_ID = "tw-tauraroa-school-001"
DOCUMENT_ID = "doc-asbestos-survey-rev0"


source_document = SourceDocument(
    id=DOCUMENT_ID,
    workup_id=WORKUP_ID,
    file_name="38-Asbestos-Survey-_Rev_0.pdf",
    file_type="application/pdf",
    page_count=50,
    parser_version="phase-1-demo",
    ocr_status="not_required_for_demo",
    created_at=NOW,
)

source_evidence = [
    SourceEvidence(
        id="ev-survey-type",
        document_id=DOCUMENT_ID,
        page_number=1,
        evidence_type="survey_type",
        raw_text="Asbestos Demolition Survey - Tauraroa Area School.",
        confidence=0.96,
    ),
    SourceEvidence(
        id="ev-r10-11-cladding-320",
        document_id=DOCUMENT_ID,
        page_number=13,
        evidence_type="register_item",
        raw_text="External / Building Envelope - flat cladding, fibre cement sheet, 320 sqm, Class B.",
        confidence=0.91,
    ),
    SourceEvidence(
        id="ev-power-box-1sqm",
        document_id=DOCUMENT_ID,
        page_number=14,
        evidence_type="no_access",
        raw_text="Power box, presumed asbestos-containing material, 1 sqm, no access.",
        confidence=0.82,
    ),
    SourceEvidence(
        id="ev-chimney-aib",
        document_id=DOCUMENT_ID,
        page_number=18,
        evidence_type="limited_access",
        raw_text="Chimney hidden AIB / insulating board, Class A, limited access, further investigation required.",
        confidence=0.78,
    ),
    SourceEvidence(
        id="ev-external-cladding-920",
        document_id=DOCUMENT_ID,
        page_number=22,
        evidence_type="register_item",
        raw_text="External cladding, fibre cement sheet, 920 sqm, Class B.",
        confidence=0.9,
    ),
    SourceEvidence(
        id="ev-power-board-box",
        document_id=DOCUMENT_ID,
        page_number=24,
        evidence_type="no_access",
        raw_text="Power board box, presumed asbestos-containing material, no access, review required.",
        confidence=0.8,
    ),
]

register_items = [
    AsbestosRegisterItem(
        id="reg-external-flat-cladding-320",
        workup_id=WORKUP_ID,
        location="External / Building Envelope",
        area="R10-11",
        material="Fibre cement sheet - flat sheet",
        product_type="Flat cladding",
        extent_quantity=320,
        extent_unit="sqm",
        asbestos_result="Positive",
        fibre_type="Chrysotile presumed from register",
        friability_class="Class B",
        condition="Weathered external cladding",
        recommendation="Removal by licensed contractor before demolition works.",
        access_status="Accessible",
        source_evidence_ids=["ev-r10-11-cladding-320"],
        confidence=0.91,
        review_status="ai_draft",
    ),
    AsbestosRegisterItem(
        id="reg-power-box-1sqm",
        workup_id=WORKUP_ID,
        location="Power box",
        area="Electrical services",
        material="Suspected asbestos-containing board",
        product_type="Power box lining",
        extent_quantity=1,
        extent_unit="sqm",
        asbestos_result="Presumed",
        fibre_type=None,
        friability_class="Unknown",
        condition="Not accessed during survey",
        recommendation="Treat as provisional until isolated and inspected.",
        access_status="No Access",
        source_evidence_ids=["ev-power-box-1sqm"],
        confidence=0.82,
        review_status="review_required",
    ),
    AsbestosRegisterItem(
        id="reg-chimney-hidden-aib",
        workup_id=WORKUP_ID,
        location="Chimney / concealed area",
        area="Roof and flue zone",
        material="Asbestos insulating board",
        product_type="Insulating board",
        extent_quantity=None,
        extent_unit="provisional",
        asbestos_result="Presumed",
        fibre_type=None,
        friability_class="Class A",
        condition="Hidden and limited-access",
        recommendation="Further investigation and Class A review required before pricing is finalized.",
        access_status="Limited Access",
        source_evidence_ids=["ev-chimney-aib"],
        confidence=0.78,
        review_status="review_required",
    ),
    AsbestosRegisterItem(
        id="reg-external-cladding-920",
        workup_id=WORKUP_ID,
        location="External cladding",
        area="External elevations",
        material="Fibre cement sheet",
        product_type="External cladding",
        extent_quantity=920,
        extent_unit="sqm",
        asbestos_result="Positive",
        fibre_type="Chrysotile presumed from register",
        friability_class="Class B",
        condition="External sheet material",
        recommendation="Controlled Class B removal and disposal.",
        access_status="Accessible",
        source_evidence_ids=["ev-external-cladding-920"],
        confidence=0.9,
        review_status="ai_draft",
    ),
    AsbestosRegisterItem(
        id="reg-power-board-box",
        workup_id=WORKUP_ID,
        location="Power board box",
        area="Electrical services",
        material="Suspected asbestos-containing material",
        product_type="Power board enclosure",
        extent_quantity=None,
        extent_unit="provisional",
        asbestos_result="Presumed",
        fibre_type=None,
        friability_class="Unknown",
        condition="Not accessed during survey",
        recommendation="Client to provide isolation/access; estimator to confirm allowance.",
        access_status="No Access",
        source_evidence_ids=["ev-power-board-box"],
        confidence=0.8,
        review_status="review_required",
    ),
]

risk_flags = [
    RiskFlag(
        id="risk-class-a",
        label="Class A / friable material",
        severity="high",
        description="Chimney AIB is Class A and requires specialist review before final pricing.",
        review_status="review_required",
        source_evidence_ids=["ev-chimney-aib"],
    ),
    RiskFlag(
        id="risk-no-access",
        label="No-access areas",
        severity="attention",
        description="Power box and power board box were not accessed and must remain provisional.",
        review_status="review_required",
        source_evidence_ids=["ev-power-box-1sqm", "ev-power-board-box"],
    ),
    RiskFlag(
        id="risk-human-approval",
        label="Human approval required",
        severity="blocked",
        description="The quote cannot be exported as final until estimator approval is complete.",
        review_status="blocked",
        source_evidence_ids=[],
    ),
]

pricing_rules = [
    PricingRule(
        id="rule-site-establishment",
        name="Site establishment minimum",
        job_type="Asbestos removal and demolition",
        formula="fixed_allowance + compliance_setup",
        risk_factors=["site_controls", "documentation", "isolation_coordination"],
        default_assumptions=["Normal working hours", "Client provides site access"],
        default_exclusions=["Scaffolding", "Power isolation charges"],
        version="demo-v1",
    ),
    PricingRule(
        id="rule-class-b-sheet-removal",
        name="Class B fibre cement sheet removal",
        job_type="Asbestos removal and demolition",
        formula="quantity_sqm * unit_rate * risk_multiplier",
        risk_factors=["external_access", "sheet_fixings", "waste_handling"],
        default_assumptions=["Controlled removal by licensed contractor"],
        default_exclusions=["Structural repairs", "Reinstatement"],
        version="demo-v1",
    ),
    PricingRule(
        id="rule-class-a-provisional",
        name="Class A/friable provisional allowance",
        job_type="Asbestos removal and demolition",
        formula="provisional_allowance pending estimator confirmation",
        risk_factors=["friability", "limited_access", "assessor_clearance"],
        default_assumptions=["Class A scope subject to further inspection"],
        default_exclusions=["Additional containment if hidden scope expands"],
        version="demo-v1",
    ),
]

quote_lines = [
    QuoteLine(
        id="ql-site-establishment",
        workup_id=WORKUP_ID,
        section="Site Establishment",
        description="Installation of equipment: signage, barricades, decontamination unit, and site-specific documentation",
        quantity=1,
        unit="item",
        unit_rate=698,
        base_cost=698,
        risk_multiplier=1.0,
        margin=0.0,
        gst=104.70,
        total=802.70,
        source_evidence_ids=["ev-survey-type"],
        pricing_rule_ids=["pb-site-establishment"],
        assumptions=[
            "Client provides access, water, power, and toilet facilities.",
            "Includes WorkSafe NZ notification and toolbox meetings.",
        ],
        exclusions=["Scaffolding", "Power isolation by qualified electrician", "Independent assessor fees"],
        review_status="ai_draft",
        approval_status="not_ready",
        why="Standard Revolve site establishment line item applied because this is an asbestos demolition survey.",
    ),
    QuoteLine(
        id="ql-class-b-cladding-320",
        workup_id=WORKUP_ID,
        section="Class B Removal",
        description="Remove and dispose external flat fibre cement cladding",
        quantity=320,
        unit="sqm",
        unit_rate=80,
        base_cost=25600,
        risk_multiplier=1.0,
        margin=0.0,
        gst=3840.00,
        total=29440.00,
        source_evidence_ids=["ev-r10-11-cladding-320"],
        pricing_rule_ids=["pb-class-b-fibre-cement-sqm"],
        assumptions=["External cladding is accessible from normal work platforms.", "Minimum charge $2,500 does not apply (area above threshold)."],
        exclusions=["Replacement cladding", "Hidden fixings beyond visible sheet removal"],
        review_status="ai_draft",
        approval_status="not_ready",
        why="Mapped from a 320 sqm Class B fibre cement sheet register item at $80/sqm.",
    ),
    QuoteLine(
        id="ql-class-a-aib-provisional",
        workup_id=WORKUP_ID,
        section="Class A / Friable Removal",
        description="Provisional Class A chimney AIB investigation and removal allowance (4 pieces)",
        quantity=4,
        unit="piece",
        unit_rate=650,
        base_cost=2600,
        risk_multiplier=1.0,
        margin=0.0,
        gst=390.00,
        total=2990.00,
        source_evidence_ids=["ev-chimney-aib"],
        pricing_rule_ids=["pb-class-a-insulating-board-provisional"],
        assumptions=[
            "Allowance subject to further inspection and assessor requirements.",
            "Class A licensed contractor required for friable insulating board.",
            "Minimum charge $2,500 enforced.",
        ],
        exclusions=["Expanded containment if concealed AIB is larger than assumed"],
        review_status="review_required",
        approval_status="not_ready",
        why="Class A limited-access AIB must remain provisional until an estimator confirms scope.",
    ),
    QuoteLine(
        id="ql-no-access-investigation",
        workup_id=WORKUP_ID,
        section="Provisional / No Access",
        description="Power box and power board box — No Access (POA, full scope to be provided)",
        quantity=None,
        unit="poa",
        unit_rate=None,
        base_cost=None,
        risk_multiplier=1.0,
        margin=0.0,
        gst=None,
        total=None,
        source_evidence_ids=["ev-power-box-1sqm", "ev-power-board-box"],
        pricing_rule_ids=["pb-no-access-power-investigation"],
        assumptions=[
            "No allowance has been included for these areas.",
            "Full scope and pricing to be provided after site visit and assessor confirmation.",
        ],
        exclusions=["All work in these no-access areas is excluded from current pricing"],
        review_status="review_required",
        approval_status="not_ready",
        why="No-access presumed asbestos areas are marked POA per Revolve pattern — priced after site visit.",
    ),
    QuoteLine(
        id="ql-class-b-cladding-920",
        workup_id=WORKUP_ID,
        section="Class B Removal",
        description="Remove and dispose external fibre cement sheet cladding",
        quantity=920,
        unit="sqm",
        unit_rate=80,
        base_cost=73600,
        risk_multiplier=1.0,
        margin=0.0,
        gst=11040.00,
        total=84640.00,
        source_evidence_ids=["ev-external-cladding-920"],
        pricing_rule_ids=["pb-class-b-fibre-cement-sqm"],
        assumptions=["Sheet extent is as recorded in the survey register."],
        exclusions=["Weather delays", "Scaffolding", "Structural remediation"],
        review_status="ai_draft",
        approval_status="not_ready",
        why="Mapped from a 920 sqm Class B fibre cement sheet register item at $80/sqm.",
    ),
    QuoteLine(
        id="ql-waste-disposal",
        workup_id=WORKUP_ID,
        section="Waste / Disposal Placeholder",
        description="Certified asbestos waste disposal at approved disposal site",
        quantity=3100,
        unit="kg",
        unit_rate=0.92,
        base_cost=2852,
        risk_multiplier=1.0,
        margin=0.0,
        gst=427.80,
        total=3279.80,
        source_evidence_ids=["ev-r10-11-cladding-320", "ev-external-cladding-920"],
        pricing_rule_ids=["pb-waste-disposal-placeholder"],
        assumptions=[
            "Waste tonnage estimated from total removal area (1,240 sqm × ~2.5 kg/sqm).",
            "Estimator should refine based on actual waste tonnage.",
        ],
        exclusions=["Contaminated soil disposal", "Unexpected mixed demolition waste"],
        review_status="ai_draft",
        approval_status="not_ready",
        why="Per-kg asbestos waste disposal at $0.92/kg (Revolve RAS-1285 rate).",
    ),
    QuoteLine(
        id="ql-encapsulation",
        workup_id=WORKUP_ID,
        section="Encapsulation / Provisional Allowance",
        description="ABC Fibre Lock encapsulant for residual fibres on porous surfaces",
        quantity=50,
        unit="sqm",
        unit_rate=34,
        base_cost=1700,
        risk_multiplier=1.0,
        margin=0.0,
        gst=255.00,
        total=1955.00,
        source_evidence_ids=["ev-chimney-aib", "ev-power-box-1sqm"],
        pricing_rule_ids=["pb-encapsulation-provisional"],
        assumptions=[
            "Used where removal exposes residual contaminated surfaces (concrete, rough timber).",
            "Estimator to confirm encapsulation extent on site visit.",
        ],
        exclusions=["Long-term encapsulation maintenance"],
        review_status="review_required",
        approval_status="not_ready",
        why="Provisional encapsulant allowance at $34/sqm (Revolve RAS-1285 pattern).",
    ),
]

estimator_edits = [
    EstimatorEdit(
        id="edit-demo-rate-note",
        workup_id=WORKUP_ID,
        entity_type="quote_line",
        entity_id="ql-class-b-cladding-320",
        field_name="unit_rate",
        previous_value=75,
        new_value=80,
        reason="Demo edit showing how estimator changes become training data.",
        user_id="estimator-demo",
        created_at=NOW,
    )
]

audit_events = [
    AuditEvent(
        id="audit-created",
        workup_id=WORKUP_ID,
        actor_type="system",
        actor_id="tracequote-demo",
        event_type="workup.created",
        payload={"client_name": "Tauraroa Area School"},
        created_at=NOW,
    ),
    AuditEvent(
        id="audit-document-uploaded",
        workup_id=WORKUP_ID,
        actor_type="system",
        actor_id="tracequote-demo",
        event_type="document.uploaded",
        payload={"file_name": source_document.file_name, "page_count": source_document.page_count},
        created_at=NOW,
    ),
    AuditEvent(
        id="audit-extraction-generated",
        workup_id=WORKUP_ID,
        actor_type="system",
        actor_id="tracequote-demo",
        event_type="extraction.generated",
        payload={"register_items": len(register_items), "risk_flags": len(risk_flags)},
        created_at=NOW,
    ),
    AuditEvent(
        id="audit-quote-generated",
        workup_id=WORKUP_ID,
        actor_type="system",
        actor_id="tracequote-demo",
        event_type="quote_line.generated",
        payload={"quote_lines": len(quote_lines), "export_status": "blocked"},
        created_at=NOW,
    ),
]


demo_workup = QuoteWorkup(
    id=WORKUP_ID,
    client_name="Tauraroa Area School",
    site_address="Tauraroa Area School, Northland, New Zealand",
    job_type="Asbestos removal and demolition",
    survey_type="Asbestos Demolition Survey",
    status="approval_required",
    assigned_estimator_id="estimator-demo",
    due_date="2026-05-30",
    created_at=NOW,
    updated_at=NOW,
    documents=[source_document],
    source_evidence=source_evidence,
    register_items=register_items,
    risk_flags=risk_flags,
    quote_lines=quote_lines,
    pricing_rules=pricing_rules,
    estimator_edits=estimator_edits,
    audit_events=audit_events,
    assumptions=[
        "Client provides safe site access, water, toilet facilities, and parking.",
        "Electrical isolation is completed by others before access to power boxes.",
        "Class A/friable scope remains provisional until further investigation confirms extent.",
        "Work is subject to estimator review and final human approval.",
    ],
    exclusions=[
        "Scaffolding and elevated work platforms unless separately included.",
        "Power disconnection, reconnection, and live electrical works.",
        "Structural repairs, reinstatement, painting, or replacement cladding.",
        "Regulatory approval or licensed assessor certification by TraceQuote AI.",
    ],
    export_status="blocked",
)


def get_demo_workup() -> QuoteWorkup:
    return demo_workup
