import type { QuoteWorkup } from "./types";

export const demoWorkup: QuoteWorkup = {
  id: "tw-tauraroa-school-001",
  client_name: "Tauraroa Area School",
  site_address: "Tauraroa Area School, Northland, New Zealand",
  job_type: "Asbestos removal and demolition",
  survey_type: "Asbestos Demolition Survey",
  status: "approval_required",
  assigned_estimator_id: "estimator-demo",
  due_date: "2026-05-30",
  created_at: "2026-05-23T09:00:00Z",
  updated_at: "2026-05-23T09:00:00Z",
  documents: [
    {
      id: "doc-asbestos-survey-rev0",
      workup_id: "tw-tauraroa-school-001",
      file_name: "38-Asbestos-Survey-_Rev_0.pdf",
      file_type: "application/pdf",
      page_count: 50,
      parser_version: "phase-1-demo",
      ocr_status: "not_required_for_demo",
      created_at: "2026-05-23T09:00:00Z",
    },
  ],
  source_evidence: [
    {
      id: "ev-survey-type",
      document_id: "doc-asbestos-survey-rev0",
      page_number: 1,
      evidence_type: "survey_type",
      raw_text: "Asbestos Demolition Survey - Tauraroa Area School.",
      confidence: 0.96,
    },
    {
      id: "ev-r10-11-cladding-320",
      document_id: "doc-asbestos-survey-rev0",
      page_number: 13,
      evidence_type: "register_item",
      raw_text:
        "External / Building Envelope - flat cladding, fibre cement sheet, 320 sqm, Class B.",
      confidence: 0.91,
    },
    {
      id: "ev-power-box-1sqm",
      document_id: "doc-asbestos-survey-rev0",
      page_number: 14,
      evidence_type: "no_access",
      raw_text: "Power box, presumed asbestos-containing material, 1 sqm, no access.",
      confidence: 0.82,
    },
    {
      id: "ev-chimney-aib",
      document_id: "doc-asbestos-survey-rev0",
      page_number: 18,
      evidence_type: "limited_access",
      raw_text:
        "Chimney hidden AIB / insulating board, Class A, limited access, further investigation required.",
      confidence: 0.78,
    },
    {
      id: "ev-external-cladding-920",
      document_id: "doc-asbestos-survey-rev0",
      page_number: 22,
      evidence_type: "register_item",
      raw_text: "External cladding, fibre cement sheet, 920 sqm, Class B.",
      confidence: 0.9,
    },
    {
      id: "ev-power-board-box",
      document_id: "doc-asbestos-survey-rev0",
      page_number: 24,
      evidence_type: "no_access",
      raw_text:
        "Power board box, presumed asbestos-containing material, no access, review required.",
      confidence: 0.8,
    },
  ],
  register_items: [
    {
      id: "reg-external-flat-cladding-320",
      workup_id: "tw-tauraroa-school-001",
      location: "External / Building Envelope",
      area: "R10-11",
      material: "Fibre cement sheet - flat sheet",
      product_type: "Flat cladding",
      extent_quantity: 320,
      extent_unit: "sqm",
      asbestos_result: "Positive",
      fibre_type: "Chrysotile presumed from register",
      friability_class: "Class B",
      condition: "Weathered external cladding",
      recommendation: "Removal by licensed contractor before demolition works.",
      access_status: "Accessible",
      source_evidence_ids: ["ev-r10-11-cladding-320"],
      confidence: 0.91,
      review_status: "ai_draft",
    },
    {
      id: "reg-power-box-1sqm",
      workup_id: "tw-tauraroa-school-001",
      location: "Power box",
      area: "Electrical services",
      material: "Suspected asbestos-containing board",
      product_type: "Power box lining",
      extent_quantity: 1,
      extent_unit: "sqm",
      asbestos_result: "Presumed",
      fibre_type: null,
      friability_class: "Unknown",
      condition: "Not accessed during survey",
      recommendation: "Treat as provisional until isolated and inspected.",
      access_status: "No Access",
      source_evidence_ids: ["ev-power-box-1sqm"],
      confidence: 0.82,
      review_status: "review_required",
    },
    {
      id: "reg-chimney-hidden-aib",
      workup_id: "tw-tauraroa-school-001",
      location: "Chimney / concealed area",
      area: "Roof and flue zone",
      material: "Asbestos insulating board",
      product_type: "Insulating board",
      extent_quantity: null,
      extent_unit: "provisional",
      asbestos_result: "Presumed",
      fibre_type: null,
      friability_class: "Class A",
      condition: "Hidden and limited-access",
      recommendation:
        "Further investigation and Class A review required before pricing is finalized.",
      access_status: "Limited Access",
      source_evidence_ids: ["ev-chimney-aib"],
      confidence: 0.78,
      review_status: "review_required",
    },
    {
      id: "reg-external-cladding-920",
      workup_id: "tw-tauraroa-school-001",
      location: "External cladding",
      area: "External elevations",
      material: "Fibre cement sheet",
      product_type: "External cladding",
      extent_quantity: 920,
      extent_unit: "sqm",
      asbestos_result: "Positive",
      fibre_type: "Chrysotile presumed from register",
      friability_class: "Class B",
      condition: "External sheet material",
      recommendation: "Controlled Class B removal and disposal.",
      access_status: "Accessible",
      source_evidence_ids: ["ev-external-cladding-920"],
      confidence: 0.9,
      review_status: "ai_draft",
    },
    {
      id: "reg-power-board-box",
      workup_id: "tw-tauraroa-school-001",
      location: "Power board box",
      area: "Electrical services",
      material: "Suspected asbestos-containing material",
      product_type: "Power board enclosure",
      extent_quantity: null,
      extent_unit: "provisional",
      asbestos_result: "Presumed",
      fibre_type: null,
      friability_class: "Unknown",
      condition: "Not accessed during survey",
      recommendation: "Client to provide isolation/access; estimator to confirm allowance.",
      access_status: "No Access",
      source_evidence_ids: ["ev-power-board-box"],
      confidence: 0.8,
      review_status: "review_required",
    },
  ],
  risk_flags: [
    {
      id: "risk-class-a",
      label: "Class A / friable material",
      severity: "high",
      description: "Chimney AIB is Class A and requires specialist review before final pricing.",
      review_status: "review_required",
      source_evidence_ids: ["ev-chimney-aib"],
    },
    {
      id: "risk-no-access",
      label: "No-access areas",
      severity: "attention",
      description: "Power box and power board box were not accessed and must remain provisional.",
      review_status: "review_required",
      source_evidence_ids: ["ev-power-box-1sqm", "ev-power-board-box"],
    },
    {
      id: "risk-human-approval",
      label: "Human approval required",
      severity: "blocked",
      description: "The quote cannot be exported as final until estimator approval is complete.",
      review_status: "blocked",
      source_evidence_ids: [],
    },
  ],
  pricing_rules: [
    {
      id: "rule-site-establishment",
      name: "Site establishment minimum",
      job_type: "Asbestos removal and demolition",
      formula: "fixed_allowance + compliance_setup",
      risk_factors: ["site_controls", "documentation", "isolation_coordination"],
      default_assumptions: ["Normal working hours", "Client provides site access"],
      default_exclusions: ["Scaffolding", "Power isolation charges"],
      version: "demo-v1",
    },
    {
      id: "rule-class-b-sheet-removal",
      name: "Class B fibre cement sheet removal",
      job_type: "Asbestos removal and demolition",
      formula: "quantity_sqm * unit_rate * risk_multiplier",
      risk_factors: ["external_access", "sheet_fixings", "waste_handling"],
      default_assumptions: ["Controlled removal by licensed contractor"],
      default_exclusions: ["Structural repairs", "Reinstatement"],
      version: "demo-v1",
    },
    {
      id: "rule-class-a-provisional",
      name: "Class A/friable provisional allowance",
      job_type: "Asbestos removal and demolition",
      formula: "provisional_allowance pending estimator confirmation",
      risk_factors: ["friability", "limited_access", "assessor_clearance"],
      default_assumptions: ["Class A scope subject to further inspection"],
      default_exclusions: ["Additional containment if hidden scope expands"],
      version: "demo-v1",
    },
  ],
  quote_lines: [
    {
      id: "ql-site-establishment",
      workup_id: "tw-tauraroa-school-001",
      section: "Site establishment",
      description: "Site establishment, compliance documentation, controlled work area setup",
      quantity: 1,
      unit: "item",
      unit_rate: 2850,
      base_cost: 2850,
      risk_multiplier: 1,
      margin: 0.18,
      gst: 504.45,
      total: 3867.45,
      source_evidence_ids: ["ev-survey-type"],
      pricing_rule_ids: ["rule-site-establishment"],
      assumptions: ["Client provides access, water, and toilet facilities"],
      exclusions: ["Scaffolding", "Power isolation charges"],
      review_status: "ai_draft",
      approval_status: "not_ready",
      why: "Included because the uploaded document is an asbestos demolition survey requiring controlled site setup.",
    },
    {
      id: "ql-class-b-cladding-320",
      workup_id: "tw-tauraroa-school-001",
      section: "Class B removal",
      description: "Remove and dispose external flat fibre cement cladding",
      quantity: 320,
      unit: "sqm",
      unit_rate: 42,
      base_cost: 13440,
      risk_multiplier: 1.08,
      margin: 0.18,
      gst: 2569.19,
      total: 19697.13,
      source_evidence_ids: ["ev-r10-11-cladding-320"],
      pricing_rule_ids: ["rule-class-b-sheet-removal"],
      assumptions: ["External cladding is accessible from normal work platforms"],
      exclusions: ["Replacement cladding", "Hidden fixings beyond visible sheet removal"],
      review_status: "ai_draft",
      approval_status: "not_ready",
      why: "Mapped from a 320 sqm Class B fibre cement sheet register item.",
    },
    {
      id: "ql-class-a-aib-provisional",
      workup_id: "tw-tauraroa-school-001",
      section: "Class A/friable removal",
      description: "Provisional Class A chimney AIB investigation and removal allowance",
      quantity: null,
      unit: "provisional",
      unit_rate: null,
      base_cost: 7500,
      risk_multiplier: 1.25,
      margin: 0.18,
      gst: 1659.38,
      total: 12721.88,
      source_evidence_ids: ["ev-chimney-aib"],
      pricing_rule_ids: ["rule-class-a-provisional"],
      assumptions: ["Allowance subject to further inspection and assessor requirements"],
      exclusions: ["Expanded containment if concealed AIB is larger than assumed"],
      review_status: "review_required",
      approval_status: "not_ready",
      why: "Class A limited-access AIB must remain provisional until an estimator confirms scope.",
    },
    {
      id: "ql-no-access-investigation",
      workup_id: "tw-tauraroa-school-001",
      section: "Provisional/no-access investigation",
      description: "Power box and power board box investigation allowance",
      quantity: 2,
      unit: "locations",
      unit_rate: 650,
      base_cost: 1300,
      risk_multiplier: 1.15,
      margin: 0.18,
      gst: 264.61,
      total: 2028.71,
      source_evidence_ids: ["ev-power-box-1sqm", "ev-power-board-box"],
      pricing_rule_ids: ["rule-class-a-provisional"],
      assumptions: ["Electrical isolation completed by others before access"],
      exclusions: ["Electrical disconnection or reinstatement"],
      review_status: "review_required",
      approval_status: "not_ready",
      why: "No-access presumed asbestos areas must be priced as provisional and reviewed.",
    },
    {
      id: "ql-class-b-cladding-920",
      workup_id: "tw-tauraroa-school-001",
      section: "Class B removal",
      description: "Remove and dispose external fibre cement sheet cladding",
      quantity: 920,
      unit: "sqm",
      unit_rate: 39,
      base_cost: 35880,
      risk_multiplier: 1.05,
      margin: 0.18,
      gst: 6668.3,
      total: 51123.62,
      source_evidence_ids: ["ev-external-cladding-920"],
      pricing_rule_ids: ["rule-class-b-sheet-removal"],
      assumptions: ["Sheet extent is as recorded in the survey register"],
      exclusions: ["Weather delays", "Scaffolding", "Structural remediation"],
      review_status: "ai_draft",
      approval_status: "not_ready",
      why: "Mapped from a 920 sqm Class B fibre cement sheet register item.",
    },
    {
      id: "ql-waste-disposal",
      workup_id: "tw-tauraroa-school-001",
      section: "Waste disposal",
      description: "Bagging, transport, and compliant asbestos waste disposal allowance",
      quantity: 1240,
      unit: "sqm basis",
      unit_rate: 8.5,
      base_cost: 10540,
      risk_multiplier: 1.05,
      margin: 0.18,
      gst: 1958.86,
      total: 15017.92,
      source_evidence_ids: ["ev-r10-11-cladding-320", "ev-external-cladding-920"],
      pricing_rule_ids: ["rule-class-b-sheet-removal"],
      assumptions: ["Waste volume follows recorded sheet extent"],
      exclusions: ["Contaminated soil disposal", "Unexpected mixed demolition waste"],
      review_status: "ai_draft",
      approval_status: "not_ready",
      why: "Waste allowance is derived from the combined Class B sheet extent.",
    },
    {
      id: "ql-encapsulation",
      workup_id: "tw-tauraroa-school-001",
      section: "Encapsulation/provisional allowance",
      description: "Encapsulation or make-safe allowance for disturbed edges and residual surfaces",
      quantity: 1,
      unit: "allowance",
      unit_rate: 1850,
      base_cost: 1850,
      risk_multiplier: 1.1,
      margin: 0.18,
      gst: 360.19,
      total: 2761.49,
      source_evidence_ids: ["ev-chimney-aib", "ev-power-box-1sqm"],
      pricing_rule_ids: ["rule-class-a-provisional"],
      assumptions: ["Used only where removal exposes residual contaminated surfaces"],
      exclusions: ["Long-term encapsulation maintenance"],
      review_status: "review_required",
      approval_status: "not_ready",
      why: "Provisional allowance linked to Class A and no-access uncertainty.",
    },
  ],
  estimator_edits: [
    {
      id: "edit-demo-rate-note",
      workup_id: "tw-tauraroa-school-001",
      entity_type: "quote_line",
      entity_id: "ql-class-b-cladding-320",
      field_name: "unit_rate",
      previous_value: 40,
      new_value: 42,
      reason: "Demo edit showing how estimator changes become training data.",
      user_id: "estimator-demo",
      created_at: "2026-05-23T09:00:00Z",
    },
  ],
  audit_events: [
    {
      id: "audit-created",
      workup_id: "tw-tauraroa-school-001",
      actor_type: "system",
      actor_id: "tracequote-demo",
      event_type: "workup.created",
      payload: { client_name: "Tauraroa Area School" },
      created_at: "2026-05-23T09:00:00Z",
    },
    {
      id: "audit-document-uploaded",
      workup_id: "tw-tauraroa-school-001",
      actor_type: "system",
      actor_id: "tracequote-demo",
      event_type: "document.uploaded",
      payload: { file_name: "38-Asbestos-Survey-_Rev_0.pdf", page_count: 50 },
      created_at: "2026-05-23T09:00:00Z",
    },
    {
      id: "audit-extraction-generated",
      workup_id: "tw-tauraroa-school-001",
      actor_type: "system",
      actor_id: "tracequote-demo",
      event_type: "extraction.generated",
      payload: { register_items: 5, risk_flags: 3 },
      created_at: "2026-05-23T09:00:00Z",
    },
    {
      id: "audit-quote-generated",
      workup_id: "tw-tauraroa-school-001",
      actor_type: "system",
      actor_id: "tracequote-demo",
      event_type: "quote_line.generated",
      payload: { quote_lines: 7, export_status: "blocked" },
      created_at: "2026-05-23T09:00:00Z",
    },
  ],
  assumptions: [
    "Client provides safe site access, water, toilet facilities, and parking.",
    "Electrical isolation is completed by others before access to power boxes.",
    "Class A/friable scope remains provisional until further investigation confirms extent.",
    "Work is subject to estimator review and final human approval.",
  ],
  exclusions: [
    "Scaffolding and elevated work platforms unless separately included.",
    "Power disconnection, reconnection, and live electrical works.",
    "Structural repairs, reinstatement, painting, or replacement cladding.",
    "Regulatory approval or licensed assessor certification by TraceQuote AI.",
  ],
  export_status: "blocked",
};

export function getEvidenceLabel(workup: QuoteWorkup, evidenceId: string): string {
  const evidence = workup.source_evidence.find((item) => item.id === evidenceId);
  if (!evidence) {
    return "Evidence pending";
  }
  return `p.${evidence.page_number} - ${evidence.raw_text}`;
}
